language: rust
rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
  - rust:
    - beta
    - nightly

env:
  global:
    secure: S9MdFWIfOYQQ3AaZkPPrAkgDf7rUvp7cCnEJhA+m6nZJjMe0wP7mvC4l63amU9usMZ1iGiJK59y/IQU4rpW7Ho6Y5BDbrgCaS3wOesMtygeThi/DHUb1bPyQtt/3GnhAC46LralmNvH7oeOeAGtOT6+DJjH9r56FyztzaltCxNNxhUBnNd4XylW8Uw1jVahACIcJ3PJbFhhBhcrNTFadTGsA4U5W3B8Og2VY1eZTPoWCSpzfi6hXmV3Cllr5NqBwmHVHuV7NORtvQMrREyoHE3giHlxsiem5LCDtWZILN0CUmCZYuCN3+OlpAdhWIKVly1tPadLlZNiuZrY0ETKFASfjI8bjHOUR+MhQjVj6ao8mKQIlHczuA1F8Pv3GVz25y2g3iKx1plX3ZqmfKfMJ+6HENf0zFuYe9tbyZoK3fY/J+zwhvTX0CURkkw7kTYVK755aNuQ6mnG9h8C8xGGX7ob2K+a1inRAazTMFgZODJor+O3f8SmSpcEXkcaYwviEqlRfWVFd8HorQb2SZsQI1IPV9oSEX3TDzG0RGsCCtGwxkkk5mibPn3j87cBzlQKIrkQ3KKFApj9rhesJmUnhsKNaqXth7pySMt8DhMySV7rQkb+gM4E5peHhZ09sZOl3KwPtjyMlzqJn/oF1nOdIRKYMk1e54jcw9f2tHoKBEMc=

after_success:
- if [ -n "$TRAVIS_PULL_REQUEST" ] && [ "$TRAVIS_RUST_VERSION" == "stable" ]; then

  git config --global user.email "skorezore@gmail.com";
  git config --global user.name "not-skorezore";

  git clone https://${GH_TOKEN}@github.com/skorezore/skorezore.github.io;
  git clone https://${GH_TOKEN}@github.com/skorezore/rusterizer;

  cd rusterizer;
  cargo doc --no-deps;

  cd ../skorezore.github.io

  rm -rf rusterizer/documentation;
  mkdir rusterizer/documentation;
  cp -a ../rusterizer/target/doc/. rusterizer/documentation;

  git add -A;
  git commit -m"Updating rusterizer documentation for ${TRAVIS_COMMIT}.";
  git push --force --quiet;

  fi
